### ISSUE TITLE
DIY Tool - Letter to Landlord re: Security Deposit

### ISSUE THREAD

**Issue by normon66** [mplp/docassemble-MichiganLetterToLandlordReRet#1]

**Comment by ekressmiller** [comment]
@normon66 I think we're going to try to launch this for real at the end of the month! There are a few things I think we need to do to get it launch ready --mostly just implementing stuff that got figured out after you completed this.  I will add those as separate issues. (And let me know if you think of anything additional.) Let me know if you have preferences for whether you or I handle these.

**Comment by normon66** [comment]
All issues/enhancements have been implemented and published to both the dev and prod servers. Good to go!
