### ISSUE TITLE
ID MLH intro landing: 
User feedback: bug
(`MLH_intro_landing`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MichiganLetterToLandlordReRet#13]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `MLH intro landing`
Details | test bug - delete
Variable being sought | `MLH_intro_landing`
Package version | `playground`
Filename | `docassemble.playground5LetterSecurityDeposit:michigan_letter_to_landlord_re__ret.yml`

**Comment by normon66** [comment]
testing feedback form
