### ISSUE TITLE
ID phone number: 
User feedback: bug
(`users[0].phone_number`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MichiganLetterToLandlordReRet#14]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `phone number`
Details | When I enter fewer than the expected number of digits for a phone number, a pink banner appears up top saying "Hey, dummy!"
Variable being sought | `users[0].phone_number`
Package version | `0.5`
Filename | `docassemble.MichiganLetterToLandlordReRet:data/questions/michigan_letter_to_landlord_re__ret.yml`

**Comment by ekressmiller** [comment]
![image](https://github.com/mplp/docassemble-MichiganLetterToLandlordReRet/assets/110936328/8689ff7a-49b0-4518-8480-4084eb090395)

**Comment by ekressmiller** [comment]
This reminds me we should maybe decide what if any validation we want to do on phone numbers.
