### ISSUE TITLE
update github_repo_name 

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-MichiganLetterToLandlordReRet#36]
Please update github_repo_name to  “docassemble-UserFeedback”

This will send any actual user feedback to private repo.

**Comment by normon66** [comment]
@ekressmiller - are you familiar with a reliable way to check which server is being used (dev or prod) via docassemble?

If that can be determined, the github repo could potentially be dynamic, i.e. using the individual repo on the dev server but the UserFeedback repo on the prod server:

`github_repo_name = 'docassemble-UserFeedback' if daconfig.get('debug', true) else 'docassemble-MichiganLetterToLandlordReRet'`

**Comment by ekressmiller** [comment]
that's a good idea!  Referring to the value of debug (like in the feedback form) is the only way I know to do that.

**Comment by ekressmiller** [comment]
@normon66 but if that will take a little work/time, my preference would probably be to just change it the simple way for now and follow up with the fancy version afterward, since I'd like to to have all day tomorrow to do final testing and any quick fixes.
