### ISSUE TITLE
glitch in live version

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-MichiganLetterToLandlordReRet#45]
From Kim: I think there's a glitch in the live version of the LL letter. Where it used to ask for the visitor's name, now it asks this:

![image](https://github.com/user-attachments/assets/f14d9b56-ed7d-4e11-ad3f-718c5e12120a)

EKM just updated Docassemble and Framework yesterday, so it's possible that messed something up?

**Comment by ekressmiller** [comment]
fixed for now via commit db771d66be0b87fba9c26c8bd202f0c80dfb9b28

It seems like the interview started using the users[i] code from this interview instead of the users[0] code from ql_baseline when it ran users.gather()

Asked about this in Teams -- I vaguely remember a mention a few weeks aback about a change to users[0] vs. users[i] customization, but it was _supposed_ to be non-breaking.

**Comment by normon66** [comment]
@ekressmiller - thanks for the quick attention to this. Michelle's response in Teams seems to perfectly support the fix you made - good thinking.

**Comment by ekressmiller** [comment]
yes! or as Quinten points out, we can do this conditionally in a single code block doing something like what they did in this commit:  https://github.com/SuffolkLITLab/docassemble-AssemblyLine/pull/854/files

Closing this now.
