### ISSUE TITLE
Minor: avoid periods in the quetion attribute (i.e. page headers)

### ISSUE THREAD

**Issue by BryceStevenWilley** [mplp/docassemble-MichiganLetterToLandlordReRet#5]
Not a deal-breaker, but a bit cleaner and more readable

**Comment by normon66** [comment]
@BryceStevenWilley - just to be sure I understand you correctly, you mean as with the image below?

![image](https://github.com/mplp/docassemble-MichiganLetterToLandlordReRet/assets/32527754/1d46b741-9c65-4b3f-a1bb-6bde3699eaff)

**Comment by BryceStevenWilley** [comment]
Yes, that is what I meant, sorry!
